// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzjpobyybalflttltnjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6anBvYnl5YmFsZmx0dGx0bmpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMTc5NTYsImV4cCI6MjA1MzY5Mzk1Nn0.Lt_92RahhfvV2jNqun9_p85o41dzOcwzcdz-WBWWXsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);